spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
logging:
  level:
    com:
      demo:
        demo:
          mapper: debug
pagehelper:
  auto-dialect: mysql
